# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
